vm_list = [
    {
        :name => "k8s-master",
        :ip => "192.168.66.11",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "k8s-worker1",
        :ip => "192.168.66.12",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "k8s-worker2",
        :ip => "192.168.66.13",
        :mem => "2048",
        :cpu => "2"
    }
]

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/jammy64"
    vm_list.each do |item|
        config.vm.define item[:name] do |vm_config|
            vm_config.vm.hostname = item[:name]
            vm_config.vm.network "private_network", ip: item[:ip]
            vm_config.vm.provider "virtualbox" do |vb|
                vb.memory = item[:mem];
                vb.cpus = item[:cpu];
                vb.name = item[:name];
            end
            vm_config.vm.provision "shell", path: "scripts/setup.sh"
        end
    end
end